name: Minify Workflow
on:
  push:
    branches: [ main, master, minify-action ]

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: Create unified file
        run: 
          touch LwdElements.min.js && > LwdElements.min.js

      - name: Copy all files
        run:
          while read p; do cat "$p" >> LwdElements.min.js; done < minify_order;

      - name: Minify the files
        uses: nizarmah/auto-minify@v3
        with:
          # Directory that contains the files you want to minify. Defaults to current directory (.)
          directory: ./LwdElements.min.js
          # Directory that contains the minified files. Defaults to same directory
          output: .
          # Overwrites the existing files with the minified version. Defaults to false.
          overwrite: true

      - name: auto commit the minified file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "bot: Add auto minified files"
          branch: ${{ github.ref }}
